alias vm="VBoxManage"
alias vms="VBoxManage list vms"
alias running="VBoxManage list runningvms"
alias modvm="VBoxManage modifyvm"
alias start="VBoxManage startvm"
alias ctlvm="VBoxManage controlvm"
alias showvm="VBoxManage showvminfo"
