#!/bin/sh

### BEGIN INIT INFO
# Provides:          nmapper
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Service to auto-launch nmap.
# Description:       Service to auto-launch nmap. 
#                    Starts default network and port scans every five minutes.
### END INIT INFO

. /lib/lsb/init-functions

# /etc/init.d/nmapper: start and stop the nmapper daemon

# Source config if available.  Sane defaults otherwise.
[ -e '/etc/nmapper.conf' ] && . /etc/nmapper.conf

# Process' files
PREFIX=`date +%y%m%d%H%M`
PIDFILE='/var/run/nmapper.pid'
DATA=${DATA:-'/opt/nmapper/'}

[ -d $DATA ] || mkdir -p $DATA

# Process' binaries
NMAP=${NMAPBIN:-which nmap}


start() {
  log_daemon_msg "Starting nmapper daemon" "nmapper"


  start-stop-daemon --pidfile $PIDFILE -m \
  -b -d $DATA \
  --start -x $NMAP \

  log_success_msg "nmapper: started successfully"
  exit 0
}

stop() {
  log_daemon_msg "Stopping nmapper daemon" "nmapper"

  start-stop-daemon --pidfile $PIDFILE \
  --stop -x $NMAP \
  --signal 9


  rm -f $PIDFILE

  log_success_msg "nmapper: stopped"
  exit 0
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|force-reload)
    stop
    start
    ;;
  status)
    status_of_proc -p $PIDFILE "$NMAP" nmapper
    exit $?
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 1
esac
exit 0

